-- Secure Authentication System — Seed Data
-- Run AFTER schema.sql. Provides sample data so dashboards aren't empty on first run.
-- NOTE: Run `node src/utils/createAdmin.js` (see backend) to create a real admin
-- account with a properly bcrypt-hashed password instead of relying on this file
-- for login credentials. This file is mainly for log/alert sample data.

USE secure_auth_system;

-- Sample login logs for demo (not tied to a real user id — user_id NULL is fine,
-- FK is ON DELETE SET NULL). Replace 1 with a real user id after you've registered
-- a test account if you want logs tied to that account specifically.

INSERT INTO login_logs (user_id, email_attempted, ip_address, user_agent, status, is_suspicious, created_at) VALUES
(NULL, 'demo.user@example.com', '203.0.113.10', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', 'success', FALSE, NOW() - INTERVAL 2 DAY),
(NULL, 'demo.user@example.com', '203.0.113.10', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', 'failed_password', FALSE, NOW() - INTERVAL 1 DAY),
(NULL, 'demo.user@example.com', '198.51.100.23', 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0)', 'success', TRUE, NOW() - INTERVAL 12 HOUR),
(NULL, 'unknown@example.com', '198.51.100.50', 'curl/8.1.2', 'failed_no_user', FALSE, NOW() - INTERVAL 6 HOUR),
(NULL, 'demo.user@example.com', '198.51.100.50', 'curl/8.1.2', 'failed_password', TRUE, NOW() - INTERVAL 5 HOUR),
(NULL, 'demo.user@example.com', '198.51.100.50', 'curl/8.1.2', 'failed_password', TRUE, NOW() - INTERVAL 5 HOUR),
(NULL, 'demo.user@example.com', '198.51.100.50', 'curl/8.1.2', 'failed_password', TRUE, NOW() - INTERVAL 4 HOUR);

-- Note: real alerts/users should be generated by actually using the app
-- (registering, triggering lockouts, etc.) so the data is consistent with
-- bcrypt hashes, JWT sessions, and FK relationships. This seed file only
-- exists to make the admin Login Logs table non-empty on a fresh demo.
